engines:
 rubocop:
   enabled: true
   exclude_paths:
     - config/engines.yml
     - 'app/main/index.js'
 duplication:
   enabled: true
   exclude_paths:
     - config/engines.yml
 metrics:
   enabled: true
   exclude_paths:
     - config/engines.yml
     - 'app/main/index.js'
 coverage:
   enabled: true
   exclude_paths:
     - config/engines.yml
     - 'app/main/index.js'
exclude_paths:
  - .bundle/
  - spec/**/*
  - benchmarks/**/*
  - 'app/main/index.js'